### PR TITLE
Linkedlist singly and doubly

### PR DESCRIPTION
**Pull request by alanpjohn**
**6** new classes have been added for the programmer to interact with:
- linkedlist
  - LinkedListNode
  - LinkedList
  - ForwardList
- doublylinkedlist
  - DoublyLinkedListNode
  - DoublyLinkedList
  - List

The *Node classes in both modules are the handle most of the state generation
The ForwardList and List class do not generate states directly. They just use the Node classes which renders the states

```python
# fl is an object of ForwardList
fl.push_front(3)
```
will create a node with value 3 and add it to the front of forwardlist
the states generated in this scenario would be `llnode_declare` , `llnode_next` , `ll_head` which interact with particular nodes rather than the list itself. Thus we can step by step show how the pointers and the values of nodes are altered for simple operations which would be essential for teaching purpose.

The LinkedList is a parent to the ForwardList. The ForwardList comes with all the methods and attributes needed to use the class as an container. The LinkedList class contains only a head attribute. I have designed in this way so programmers have the freedom to use this and LinkedListNode as basic building blocks to make their LinkedList method implementation. Same applies betweem the DoublyLinkedList and List classes.

> This will make the rendering process logically easier but might make technically difficult with respect to placing nodes and managing pointers between them.

### CODE REVIEW

**Comment by yatharthmathur** [comment]
Why two different kinds of linked lists?

**Comment by alanpjohn** [comment]
> Why two different kinds of linked lists?

One for doubly linked list and one for singly linked list

**Comment by alanpjohn** [comment]
Regarding the mountain of commits after that
image
I just configured codacy for our project, we were previous running on defaults which caused faulty poor results. And resolved some code style issues while i was at it

**Comment by alanpjohn** [comment]
@yatharthmathur is that review done?

**Review by yatharthmathur — APPROVED** [review]

**Comment by yatharthmathur** [comment]
Yea I reviewed and comment last time for that doubt about doubly linked

**Pull request merged**
