### PR TITLE
Tutorials

### PR DESCRIPTION
**Pull request by alanpjohn**
- fixed a cli bug regarding json output
- added cloud url. [more details](https://github.com/ARgorithm/Server/pull/13)

# Adding basic examples
For each example, there will be a python code file and a config file in examples
> not adding more examples till validation is complete

along with these a page will have to be added to the tutorials page
for example: https://argorithm.github.io/toolkit/tutorials/bubblesort/
> github pages does not require pull request to be merge, it is controlled locally

### CODE REVIEW

**Comment by yatharthmathur** [comment]
gg

**Comment by alanpjohn** [comment]
### Fibonacci

The tutorial for fibonacci has been added [here](https://argorithm.github.io/toolkit/tutorials/fibonacci/)
As both fibonacci and bubblesort were using `Array`, I have redone fibonacci with `Variable`

### Version oopsie

So our versioning system was not correct
we were releasing minor releases as patch releases
what we should release new features as 0.N.0 and patch fixes in 0.0.N
so to fix that we are releasing `0.1.0`

**Comment by alanpjohn** [comment]
@yatharthmathur 
just review the new fibonacci code and the tutorial made once
if its cool then merge the branch

**Comment by yatharthmathur** [comment]
Alright @TheForeverLost

**Review by yatharthmathur — APPROVED** [review]

**Pull request merged**
